name: smartmarktclient
description: Engineer's Thesis - Client

version: 1.0.2+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  http: ^0.13.2
  convert: ^3.0.0
#  barcode_scan: 3.0.1
  barcode_widget: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true